# Generated by Django 4.2.7 on 2026-05-11 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_userprofile_address_userprofile_career_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('interest', 'Interest Test'), ('aptitude', 'Aptitude Test')], max_length=20)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('scores', models.JSONField(blank=True, default=dict)),
                ('top_streams', models.JSONField(blank=True, default=list)),
                ('recommended_stream', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'test_type'], name='api_assessm_user_id_05ddb6_idx'), models.Index(fields=['created_at'], name='api_assessm_created_e87b09_idx')],
            },
        ),
    ]
