# Generated by Django 4.2.7 on 2026-05-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assessmentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudeQuestionSubmission',
            fields=[
            ],
            options={
                'verbose_name': 'Aptitude Questions',
                'verbose_name_plural': 'Aptitude Questions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.assessmentsubmission',),
        ),
        migrations.CreateModel(
            name='InterestQuestionSubmission',
            fields=[
            ],
            options={
                'verbose_name': 'Interest Questions',
                'verbose_name_plural': 'Interest Questions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.assessmentsubmission',),
        ),
    ]
