# Generated by Django 4.2.7 on 2026-05-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aptitudequestionsubmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AptitudeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_key', models.CharField(max_length=100)),
                ('question_id', models.PositiveIntegerField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_option_index', models.PositiveIntegerField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Aptitude Questions',
                'verbose_name_plural': 'Aptitude Questions',
                'ordering': ['stream_key', 'display_order', 'question_id'],
            },
        ),
        migrations.CreateModel(
            name='InterestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveIntegerField(unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('emoji', models.CharField(blank=True, max_length=50)),
                ('question', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Interest Questions',
                'verbose_name_plural': 'Interest Questions',
                'ordering': ['display_order', 'question_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='aptitudequestionsubmission',
            options={'verbose_name': 'Aptitude Question Submissions', 'verbose_name_plural': 'Aptitude Question Submissions'},
        ),
        migrations.AlterModelOptions(
            name='interestquestionsubmission',
            options={'verbose_name': 'Interest Question Submissions', 'verbose_name_plural': 'Interest Question Submissions'},
        ),
        migrations.AddConstraint(
            model_name='aptitudequestion',
            constraint=models.UniqueConstraint(fields=('stream_key', 'question_id'), name='unique_aptitude_question_per_stream'),
        ),
    ]
